[project]
name = 'trmnl'
version = '0.0.1'
requires-python = '==3.12.*'
dependencies = [
    "pillow ==11.2.1",
    "requests ==2.32.3",
]

[tool.uv]
dev-dependencies = [
    "mypy ==1.15.0",
    "pytest ==8.3.5",
    "pytest-cov ==6.1.1",
]
