[project]
name = 'trmnl'
version = '0.0.1'
requires-python = '== 3.12.*'
dependencies = [
    "pillow == 11.3.0",
    "requests == 2.32.5",
]

[dependency-groups]
dev = [
    "mypy ==1.15.0",
    "pytest ==8.3.5",
    "pytest-cov ==6.1.1",
]
