[project]
name = 'trmnl'
version = '0.0.1'
requires-python = '== 3.12.*'
dependencies = [
    "pillow == 11.3.0",
    "requests == 2.32.5",
]

[dependency-groups]
dev = [
    "mypy == 1.18.2",
    "pytest == 8.4.2",
    "pytest-cov == 7.0.0",
]
