#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

log_dir='tmp/trmnl_logs'

mkdir -p "$log_dir"
cd "$log_dir"
wget \
    --accept "*.json" \
    --level=1 \
    --no-directories \
    --quiet \
    --recursive \
    --timeout=1 \
    --tries=1 \
    http://10.0.0.100:4000/logs/
