#!/bin/sh

working_dir=$(dirname "$0")
cd "$working_dir" || exit 1

if command -v uv
then
    run_python='uv run'
else
    run_python='python'
fi

if $run_python -m gather
then
    $run_python -m render
fi
